#sudo: required

language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"

language: java

jdk:
  - oraclejdk8

java:

c++:

install: 

script:
  - mkdir -p ${HOME}/.zcs-deps/
  - mkdir -p ${HOME}/.ivy2/cache
  - wget https://files.zimbra.com/repository/ant-contrib/ant-contrib-1.0b1.jar                           -O ${HOME}/.zcs-deps/ant-contrib-1.0b1.jar
  - wget https://files.zimbra.com/repository/ant-1.7.0-ziputil-patched/ant-1.7.0-ziputil-patched-1.0.jar -O ${HOME}/.zcs-deps/ant-1.7.0-ziputil-patched-1.0.jar
  - cd ..
  - git clone https://github.com/Zimbra/zm-timezones.git
  - cd zm-mailbox
  - ant -Dzimbra.buildinfo.version=1.1.1_GA_1000 test-all

after_script:
- python html2text.py /home/travis/build/rohan-ambasta/zm-mailbox/store/build/test/report/index.html
